version: '3.4'

services:
  login:
    image: login
    build:
      context: login
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1234:1234
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
